name: LootInjector
version: ${version}
main: dev.cevapi.lootinjector.paper.LootInjectorPlugin
api-version: '1.21'
authors: [CevAPI]
commands:
  lootinjector:
    description: Open LootInjector GUI / command suite
    usage: /lootinjector
    aliases: [li]
permissions:
  lootinjector.admin:
    default: op
